language: haskell

ghc:
  - 7.10.2

before_install:
#  - zlib1g-dev 
#  - libncurses5-dev

install:
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH

  # Showing Cabal configuration
  #- echo ' ' >> $HOME/.cabal/config
  #- echo 'program-default-options' >> $HOME/.cabal/config
  #- echo '  ghc-options: -pgmPcpphs -optP--cpp' >> $HOME/.cabal/config
  #- cat $HOME/.cabal/config

  # New Happy needed for haskell-src-exts
  - cabal install happy

  # New new Alex for us
  - cabal install alex
  - cabal install cpphs

  - cabal install Agda-2.4.2.5
  - wget https://github.com/agda/agda-stdlib/archive/2.4.2.5.zip /tmp/2.4.2.5.zip
  - unzip /tmp/2.4.2.5.zip -d /tmp/

script:
  - agda -i . -i /tmp/agda-stdlib-2.4.2.5/src/ ChurchRosser.lagda


notifications:
  email: false

