language: c

# explicitly request container-based infrastructure
sudo: false

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2],sources: [hvr-ghc]}}
      

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/stdlib/

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  # Number of modules compile in parallel.
  - export JOBS=2

  # The Emacs version.
  - emacs --version

  # Reading package list for `hackage.haskell.org`.
  - cabal update
  - cat $HOME/.cabal/config

  # Installing latest version of cabal-install.
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH

  - cabal install alex
  - cabal install happy
  - cabal install cpphs-1.19.3
  - cabal install Agda-2.4.2.5

  - mkdir -p $HOME/stdlib/
  - if [[ ! -e $HOME/stdlib/ ]]; then
      wget https://github.com/agda/agda-stdlib/archive/2.4.2.5.zip $HOME/stdlib/2.4.2.5.zip &&
      unzip $HOME/stdlib/2.4.2.5.zip;
    fi

script:
  - agda -i . -i $HOME/stdlib/agda-stdlib-2.4.2.5/src/ ChurchRosser.lagda


notifications:
  email: false

