language: c

# explicitly request container-based infrastructure
sudo: false

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1],sources: [hvr-ghc]}}
      

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/stdlib/

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
#  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH
  - mkdir -p $HOME/stdlib/

  # New Happy needed for haskell-src-exts
  - cabal install happy

  # new Alex for us
  - cabal install alex
  - cabal install cpphs

  - cabal --force-reinstalls install Agda-2.4.2.5
  - if [[ ! -e $HOME/stdlib/ ]];
    then
      wget https://github.com/agda/agda-stdlib/archive/2.4.2.5.zip $HOME/stdlib/2.4.2.5.zip;
      unzip $HOME/stdlib/2.4.2.5.zip
    fi

script:
  - agda -i . -i $HOME/stdlib/agda-stdlib-2.4.2.5/src/ ChurchRosser.lagda


notifications:
  email: false

